# class_data.py

CARD_MAP = {
    "card1.jpg": "Alter the Future 3x",
    "card2.jpg": "Alter the Future 3x NOW",
    "card3.jpg": "Alter the Future 5x",
    "card4.jpg": "Armageddon",
    "card5.jpg": "Attack",
    "card6.jpg": "Attack",
    "card7.jpg": "Barking Kitten",
    "card8.jpg": "Bury",
    "card9.jpg": "Cat Card",
    "card10.jpg": "Catomic Bomb",
    "card11.jpg": "Clairvoyance",
    "card12.jpg": "Clone",
    "card13.jpg": "Curse of the Cat Butt",
    "card14.jpg": "Defuse",
    "card15.jpg": "Devilcat",
    "card16.jpg": "Dig Deeper",
    "card17.jpg": "Draw From the Bottom",
    "card18.jpg": "Exploding Kitten",
    "card19.jpg": "Favor",
    "card20.jpg": "Feed The Dead",
    "card21.jpg": "Feral Cat",
    "card22.jpg": "Garbage Collection",
    "card23.jpg": "Godcat",
    "card24.jpg": "Grave Robber",
    "card25.jpg": "I'll Take That",
    "card26.jpg": "Imploding Kitten",
    "card27.jpg": "Mark",
    "card28.jpg": "Nope",
    "card29.jpg": "Personal Attack 3x",
    "card30.jpg": "Potluck",
    "card31.jpg": "Raising Heck",
    "card32.jpg": "Reveal the Future 3x",
    "card33.jpg": "Reverse",
    "card34.jpg": "See the Future 3x",
    "card35.jpg": "See the Future 5x",
    "card36.jpg": "Share the Future 3x",
    "card37.jpg": "Shuffle",
    "card38.jpg": "Shuffle NOW",
    "card39.jpg": "Skip",
    "card40.jpg": "Streaking Kitten",
    "card41.jpg": "Super Skip",
    "card42.jpg": "Swap Top and Bottom",
    "card43.jpg": "Targeted Attack 2x",
    "card44.jpg": "Tower of Power",
    "card45.jpg": "Zombie Kitten"
}
